
# They activate the theme and tell Jekyll to find your homepage content
# in /_sections. Note where "sections" starts with an underscore
# and where it doesn't. The social settings will make links to
# Twitter, etc., but only if you give the URL.

# Site settings
title: Luiz Fraga
subtitle: Desenvolvedor Front-end Jekyll.
description: >- # this means to ignore newlines until "baseurl:"
  Este site foi desenvolvido em HTML 5, sendo seu motor de funcionamento
  o CMS Jekyll.
author: Luiz Fraga
email: luizfragabr@yahoo.com.br
avatar: assets/images/avatar.jpg

#baseurl: "/jekyll-theme-prologue" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site

# Social settings
# Make sure to include the full url including protocol, e.g. https://github.com/chrisbobbe
twitter_url:
facebook_url:
googleplus_url:
instagram_url:
linkedin_url:
github_url:
pinterest_url:
slack_url:
dribbble_url:

# Google Analytics Tracking ID goes here:
google_analytics:

# The following settings are NECESSARY for the Prologue theme to run:
#theme: jekyll-theme-prologue
collections: [sections]

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]